#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

// Simple bump allocator for runtime
static uint8_t heap[1024 * 1024]; // 1MB heap
static size_t heap_ptr = 0;

// Runtime allocator function
void* rt_alloc(size_t size) {
    // Align to 8 bytes
    size = (size + 7) & ~7;
    
    if (heap_ptr + size > sizeof(heap)) {
        fprintf(stderr, "Out of memory!\n");
        exit(1);
    }
    
    void* result = &heap[heap_ptr];
    heap_ptr += size;
    return result;
}

// Runtime print function
uint64_t rt_print_int(int64_t value) {
    printf("%lld\n", value);
    fflush(stdout);
    return 0; // Return Unit (tagged 0)
}

// Note: main() is now generated by Cranelift
// This file only provides runtime support functions
