repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt (nightly)
        entry: cargo +nightly fmt --all --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo +stable clippy --all -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        entry: cargo +stable test --all
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-build
        name: cargo build (release)
        entry: cargo +stable build --all --release
        language: system
        types: [rust]
        pass_filenames: false

      - id: dprint
        name: dprint check
        entry: dprint check
        language: system
        types_or: [markdown, toml]
        pass_filenames: false
