[package]
name = "system-f-omega"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
lalrpop-util = { version = "0.22.2", features = ["lexer", "unicode"] }
logos = "0.15"
thiserror = "2.0"
ariadne = "0.5"
clap = { version = "4.0", features = ["derive"] }

# Cranelift backend dependencies
cranelift = "0.113"
cranelift-module = "0.113"
cranelift-object = "0.113"
target-lexicon = "0.12"

[build-dependencies]
lalrpop = { version = "0.22.2", features = ["lexer", "unicode"] }
